### 성공
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
  "memberId": 1,
  "screenId": 10,
  "scheduleId": 10,
  "seatNames": ["A1", "A2", "A3"]
}

### 하나의 상영에 대해 한 사람당 최대 5개의 좌석만 예매 가능합니다.
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
"memberId": 2,
"screenId": 10,
"scheduleId": 20,
"seatNames": ["A1", "A2", "A3", "B1", "B2", "B3"]
}


### 성공
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
  "memberId": 3,
  "screenId": 10,
  "scheduleId": 30,
  "seatNames": ["A1"]
}

### 성공
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
  "memberId": 3,
  "screenId": 10,
  "scheduleId": 30,
  "seatNames": ["A2"]
}

### 하나의 상영에 대해 최대 2개까지 예약할 수 있습니다.
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
  "memberId": 3,
  "screenId": 10,
  "scheduleId": 30,
  "seatNames": ["A3"]
}

### 하나의 상영에 대해 5개의 표를 예매하는 경우 좌석은 붙어있어야 합니다.
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
  "memberId": 4,
  "screenId": 10,
  "scheduleId": 40,
  "seatNames": ["A1", "B1", "C1", "D1", "E1"]
}

### 성공
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
  "memberId": 5,
  "screenId": 10,
  "scheduleId": 50,
  "seatNames": ["A1"]
}

### 이미 예매된 좌석입니다.
POST http://localhost:8081/api/v1/reservation
Content-Type: application/json

{
  "memberId": 6,
  "screenId": 10,
  "scheduleId": 50,
  "seatNames": ["A1"]
}